# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html

# Mod Properties
mod_name=CrouchSaver
mod_id=crouchsaver
mod_version=1.0
maven_group=me.lucaaa
mod_license=GPL-3.0

# Common
enabled_platforms = fabric,neoforge,forge
minecraft_version=1.21
minecraft_version_range=1.21.x

# Fabric
fabric_loader_version=0.18.4
# Fabric API is not used in the mod
# fabric_version=0.102.0+1.21
modmenu_version=11.0.3

# NeoForge
neo_version=21.0.167

# Forge
forge_full_version=1.21-51.0.33
forge_version=51.0.33