modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Luncaaa/Crouch-Saver/issues"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors = "Lucaaa"
description = '''
Keep crouching when opening a GUI or crouch when opening one on a ladder!
'''
displayURL="https://modrinth.com/project/crouch-saver" #optional
logoFile = "assets/crouchsaver/icon.png"
# A URL to query for updates for this mod. See the JSON update specification https://docs.neoforged.net/docs/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "crouchsaver.mixins.json"